training:
  seed: 42
  batch_size: 12
  num_workers: 1
  gradient_accumulation_steps: 2
  learning_rate: 0.0001
  weight_decay: 0.005
  warmup_steps: 0.05
  max_grad_norm: 5.0
  logging_steps: 25
  amp: true
  early_stopping_patience: 5
  early_stopping_threshold: 0.001

finetuning:
  seed: 42
  batch_size: 12
  num_workers: 1
  gradient_accumulation_steps: 2
  encoder_lr: 0.00002
  ctc_head_lr: 0.0001
  weight_decay: 0.005
  warmup_steps: 0.05
  max_grad_norm: 5.0
  logging_steps: 25
  amp: true
  early_stopping_patience: 5
  early_stopping_threshold: 0.001

evaluation:
  batch_size: 12
  num_workers: 1
  logging_steps: 25
  amp: true
